
services:
  azure-log-viewer:
    build: .
    image: hackinglab/azure-log-viewer:3.2
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    labels:
      - traefik.enable=true
      - traefik.http.routers.azure.rule=Host(`azure.idocker.hacking-lab.com`)
      - traefik.http.services.azure.loadbalancer.server.port=80
    volumes:
      - ./scripts:/opt/scripts
      - /opt/showmyip-docker/logs/livecd.log:/var/log/livecd.log
